### ISSUE TITLE
Frontmatter indent

### ISSUE THREAD

**Issue by sugarshin** [remarkjs/remark-lint#169]
Hi,

I need detect mixed indent with tab in Frontmatter. Is there a way?

**Comment by wooorm** [comment]
Could you provide examples of ok and not ok input?

**Comment by sugarshin** [comment]
ok ❌ 

```yaml
---
user:
  name: sugarshin
	url: github.com/sugarshin
---
```

ok ✅ 

```yaml
---
user:
  name: sugarshin
  url: github.com/sugarshin
---
```

Do you understand?
